//! build.rs — AIDL → Rust TRANSACTION_* 常量生成器
//!
//! 编译时解析 IActivityManager.aidl / IProcessObserver.aidl，按 AIDL 方法声明顺序
//! 生成 TRANSACTION_* 常量（FIRST_CALL_TRANSACTION = 1 + method_index）。
//!
//! 这样做的好处：
//! 1. 事务码直接从 AIDL 文件推导，与 AOSP aidl 编译器规则完全一致，杜绝手写硬编码错误
//! 2. 不依赖 binder crate 的 declare_binder_interface! 宏（该宏 API 随 AOSP 版本变化）
//! 3. AIDL 文件修改后自动重新生成，cargo rerun-if-changed 保证增量编译正确性

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // AIDL 文件位于上级目录 (AppOpt-master/)
    let aidl_dir = manifest_dir.parent().unwrap();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("aidl_transactions.rs");

    // 待解析的 AIDL 文件列表: (文件名, 模块名)
    let aidl_files: &[(&str, &str)] = &[
        ("IActivityManager.aidl", "IActivityManager"),
        ("IProcessObserver.aidl", "IProcessObserver"),
    ];

    let mut output = String::new();
    output.push_str("// ================================================= ========================\n");
    output.push_str("// AUTO-GENERATED by build.rs — DO NOT EDIT MANUALLY\n");
    output.push_str("//\n");
    output.push_str("// Source: IActivityManager.aidl, IProcessObserver.aidl\n");
    output.push_str("// Rule:  TRANSACTION_code = FIRST_CALL_TRANSACTION (1) + method_index\n");
    output.push_str("//        method_index 按 AIDL 接口体内方法声明顺序从 0 开始计数\n");
    output.push_str("//        这与 AOSP aidl 编译器 (frameworks/base/tools/aidl/) 的编号规则一致\n");
    output.push_str("// ================================================= ========================\n\n");

    for (aidl_name, module_name) in aidl_files {
        let aidl_path = aidl_dir.join(aidl_name);
        let content = fs::read_to_string(&aidl_path).unwrap_or_else(|e| {
            panic!(
                "build.rs: 无法读取 AIDL 文件 {}: {}",
                aidl_path.display(),
                e
            )
        });

        let methods = parse_aidl_methods(&content);

        output.push_str(&format!(
            "/// TRANSACTION_* 常量，由 {} 自动生成 (共 {} 个方法)\n",
            aidl_name,
            methods.len()
        ));
        output.push_str(&format!("pub mod {} {{\n", module_name));

        for (i, method) in methods.iter().enumerate() {
            let code = 1 + i; // FIRST_CALL_TRANSACTION = 1
            output.push_str(&format!(
                "    pub const TRANSACTION_{}: u32 = 0x{:04x}; // index={}\n",
                method, code, i
            ));
        }

        // 便捷别名：常用方法
        if *module_name == "IActivityManager" {
            output.push_str("\n    // 常用方法别名\n");
            if let Some(idx) = methods.iter().position(|m| m == "registerProcessObserver") {
                output.push_str(&format!(
                    "    pub const REGISTER_PROCESS_OBSERVER: u32 = 0x{:04x}; // registerProcessObserver @{}\n",
                    1 + idx,
                    idx
                ));
            }
            if let Some(idx) = methods.iter().position(|m| m == "unregisterProcessObserver") {
                output.push_str(&format!(
                    "    pub const UNREGISTER_PROCESS_OBSERVER: u32 = 0x{:04x}; // unregisterProcessObserver @{}\n",
                    1 + idx,
                    idx
                ));
            }
        }

        output.push_str("}\n\n");

        println!("cargo:rerun-if-changed={}", aidl_path.display());
    }

    fs::write(&dest, output).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
}

/// 解析 AIDL 文件，提取接口体内所有方法名（按声明顺序）。
///
/// AIDL 事务码编号规则：FIRST_CALL_TRANSACTION(1) + 方法在接口体中的声明序号(0-based)。
/// 这与 AOSP `frameworks/base/tools/aidl/` 的编号逻辑完全一致。
fn parse_aidl_methods(content: &str) -> Vec<String> {
    // 1. 去除注释（块注释 /* */ 和行注释 //）
    let cleaned = remove_comments(content);

    // 2. 提取 interface Body
    let body = extract_interface_body(&cleaned);

    // 3. 按分号分割，逐条解析方法声明
    let mut methods = Vec::new();
    for stmt in body.split(';') {
        let s = stmt.trim();
        if s.is_empty() {
            continue;
        }
        // 去除注解：@UnsupportedAppUsage(...), @JavaPassthrough(...), @EnforcePermission(...), @nullable 等
        let s_clean = remove_annotations(s);
        let s_clean = s_clean.trim();
        if s_clean.is_empty() {
            continue;
        }
        // 匹配方法声明: [oneway] ReturnType MethodName(ParamList)
        if let Some(name) = extract_method_name(s_clean) {
            methods.push(name);
        }
    }
    methods
}

/// 去除 AIDL 中的块注释和行注释
fn remove_comments(content: &str) -> String {
    let mut result = String::with_capacity(content.len());
    let mut chars = content.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '/' {
            match chars.peek() {
                Some('*') => {
                    // 块注释: 跳到 */
                    chars.next();
                    let mut prev = '\0';
                    while let Some(c2) = chars.next() {
                        if prev == '*' && c2 == '/' {
                            break;
                        }
                        prev = c2;
                    }
                    result.push(' ');
                }
                Some('/') => {
                    // 行注释: 跳到行尾
                    chars.next();
                    while let Some(&c2) = chars.peek() {
                        if c2 == '\n' {
                            break;
                        }
                        chars.next();
                    }
                }
                _ => {
                    result.push(c);
                }
            }
        } else {
            result.push(c);
        }
    }
    result
}

/// 去除 AIDL 注解，如 @UnsupportedAppUsage(maxTargetSdk=30, trackingBug=170729553)
fn remove_annotations(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '@' {
            // 跳过注解名（字母、数字、下划线）
            while let Some(&c2) = chars.peek() {
                if c2.is_alphanumeric() || c2 == '_' || c2 == '.' {
                    chars.next();
                } else {
                    break;
                }
            }
            // 跳过可选的 (...)，注意嵌套
            if chars.peek() == Some(&'(') {
                let mut depth = 1;
                chars.next();
                while depth > 0 {
                    match chars.next() {
                        Some('(') => depth += 1,
                        Some(')') => depth -= 1,
                        None => break,
                        _ => {}
                    }
                }
            }
            result.push(' ');
        } else {
            result.push(c);
        }
    }
    result
}

/// 提取 interface Name { ... } 的 body 部分
fn extract_interface_body(content: &str) -> &str {
    // 查找 "interface" 关键字后的第一个 '{'
    let iface_pos = match content.find("interface") {
        Some(p) => p,
        None => return "",
    };
    let brace_pos = match content[iface_pos..].find('{') {
        Some(p) => iface_pos + p + 1,
        None => return "",
    };
    let rest = &content[brace_pos..];
    // 找最后一个 '}'（接口体的结束）
    match rest.rfind('}') {
        Some(end) => &rest[..end],
        None => rest,
    }
}

/// 从方法声明中提取方法名
///
/// 方法声明格式: [oneway] ReturnType MethodName(ParamList)
/// 方法名是 '(' 之前的最后一个标识符，且前面必须有返回类型。
fn extract_method_name(s: &str) -> Option<String> {
    // 找到第一个 '(' — 方法参数列表的开始
    let paren_idx = s.find('(')?;
    let before_paren = s[..paren_idx].trim();

    // 方法名是 '(' 前的最后一个 token
    let tokens: Vec<&str> = before_paren.split_whitespace().collect();
    if tokens.len() < 2 {
        // 至少需要 "ReturnType MethodName" 两个 token
        return None;
    }

    let name_token = tokens.last()?;
    // 验证方法名是合法标识符
    let name = name_token.trim();
    if name.is_empty() {
        return None;
    }
    let first = name.chars().next()?;
    if !first.is_alphabetic() && first != '_' {
        return None;
    }
    if !name.chars().all(|c| c.is_alphanumeric() || c == '_') {
        return None;
    }

    Some(name.to_string())
}